import TopAppBar from "@/componentes/TopAppBar";
import { inter, material_symbols } from "@/fonts";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${material_symbols.variable}`}>
        <aside>
          <TopAppBar />
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
